#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone : http://www.chy1.com:8100/eureka/,http://www.chy2.com:8200/eureka/
#开启 hystrix.stream 接口
management:
  endpoints:
    web:
      exposure:
        include : hystrix.stream

spring:
  application:
    name: ribbon
---
server:
  port: 8300
spring:
  profiles: ribbon0

---
server:
  port: 8301
spring:
  profiles: ribbon1