#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone : http://www.chy1.com:8100/eureka/,http://www.chy2.com:8200/eureka/

spring:
  application:
    name: feign
server:
  port: 8800
#必须添加 默认 为false 不启用hystrix
feign:
  hystrix:
    enabled: true