#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone : http://www.chy1.com:8100/eureka/,http://www.chy2.com:8200/eureka/

spring:
  application:
    name: zipkin-client
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin-server
---
server:
  port: 8600
spring:
  profiles: env1

---
server:
  port: 8601
spring:
  profiles: env2